# Generated by Django 3.1 on 2020-10-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rentals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('size', models.IntegerField()),
                ('owner', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('house_type', models.CharField(max_length=40)),
                ('description', models.TextField()),
            ],
        ),
    ]
