# Generated by Django 3.1 on 2020-10-22 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentals',
            old_name='price',
            new_name='rent',
        ),
        migrations.AddField(
            model_name='rentals',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rentals',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='rentals',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='RentalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='images/')),
                ('rental', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rentals.rentals')),
            ],
        ),
    ]
