# Generated by Django 3.1 on 2020-10-31 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_auto_20201023_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentals',
            name='image',
        ),
        migrations.AddField(
            model_name='rentals',
            name='images',
            field=models.FileField(default='https://photos.google.com/photo/AF1QipOK45w-YPGkrI5Y-Njk8IP6eXFwisNgGkBlfJzR', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='rentalimage',
            name='images',
            field=models.FileField(default=None, upload_to='images/'),
        ),
    ]
