# Generated by Django 3.1 on 2020-12-07 19:26

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0004_organizationinvitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Realtor',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('organizations.organization',),
        ),
    ]
