# Generated by Django 3.1 on 2020-12-08 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_auto_20201208_0930'),
        ('realtors', '0002_auto_20201208_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('organizations.organizationuser',),
        ),
    ]
